sudo: required 
services:
  - docker

before_install:
  - docker build -t aamrr/docker-react -f Dockerfile.dev .
script:
  - docker run aamrr/docker-react npm run test -- --coverage  

deploy:
  provider: azure_web_apps
  username: $AZURE_WA_USERNAME       
  password: $AZURE_WA_PASSWORD   
  site: $AZURE_WA_SITE       
  skip_cleanup: true
  verbose: true
  on: master