sudo: required 
services:
  - docker

before_install:
  - docker build -t aamrr/docker-react -f Dockerfile.dev .
script:
  - docker run aamrr/docker-react npm run test -- --coverage  

deploy:
  provider: heroku
  api_key:
    secure: $API_KEY
  app: dockereact
  on: master